### ISSUE TITLE
Fix \circ everywhere

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#42]
Currently the symbol for `white bullet` `◦` is used everywhere instead of `ring operator` `∘`, because it won't render properly in PDF without using `\ensuremath`.

**Comment by Blaisorblade** [comment]
(First, thanks for this project, it's great!)

FWIW, `$\circ$` would work as well as `\ensuremath{\circ}`. `\ensuremath` works both in math and non-math mode.
But using `\ensuremath` is often discouraged, since those modes need be distinguished anyway by the author: they obey completely different rules regarding spacing and so on.

(Sorry for the LaTeX lecture you didn't ask for).

**Comment by hmemcpy** [comment]
The LaTeX lecture is great and welcome! First time ever doing something in LaTeX, so I learn quickly :)) And yeah, I've already started employing more `$..$` etc!
The initial thing was easier, because that's what pandoc produced out of the original WordPress html, so I decided to go with it!
