### ISSUE TITLE
Fun Cover

### ISSUE THREAD

**Issue by adishavit** [hmemcpy/milewski-ctfp-pdf#52]
Someone made [a printable-on-demand Lulu version](http://www.lulu.com/shop/bartosz-milewski/category-theory-for-programmers/paperback/product-23352094.html).
They made a fun cover image - maybe use that for the digital version too:
![product_thumbnail](https://user-images.githubusercontent.com/1814800/31068394-80ab0c36-a760-11e7-95d1-01298cc5f2af.jpg)

**Comment by mseri** [comment]
I hope the money for these printed copies are going to Bartosz Milewski. In that case I'd be happy to buy one. Who knows more about it?

**Comment by hmemcpy** [comment]
As far as I understand, this is just a service that prints books for that
price. Nobody else is getting paid.

On Oct 2, 2017 6:07 PM, "Marcello Seri" <notifications@github.com> wrote:

I hope the money for these printed copies are going to Bartosz Milewski. In
that case I'd be happy to buy one. Who knows more about it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hmemcpy/milewski-ctfp-pdf/issues/52#issuecomment-333563090>,
or mute the thread

**Comment by hmemcpy** [comment]
I've changed it for now :)
![image](https://user-images.githubusercontent.com/601206/31094980-ba6af4a4-a7bf-11e7-8857-870346890b44.png)

**Comment by adishavit** [comment]
Love it! 
🎇🐖🎆

**Comment by ajnsit** [comment]
Ah! I wish I had seen that earlier before putting together a cover from scratch myself. In any case, the 5.5x8.5 print ready cover is available here (https://github.com/ajnsit/milewski-ctfp-pdf-cover/blob/master/CategoryTheoryCover.pdf) in case anyone wants it.

**Comment by hmemcpy** [comment]
@ajnsit oh wow, I love this :)
Can you make just the front cover PDF? I'll try including it!

**Comment by ajnsit** [comment]
Of course! I uploaded the cover PDF here - https://github.com/ajnsit/milewski-ctfp-pdf-cover/blob/master/cover_print_front.png.pdf

**Comment by hmemcpy** [comment]
Thank you!
Something is weird about that lowercase `r` :)

**Comment by ajnsit** [comment]
The fonts seem to have gotten messed up :( I'll see how it can be fixed.

**Comment by hmemcpy** [comment]
I'm closing this for now. Replacing the coverpage is simply replacing the PDF. Will await PRs :)
