### ISSUE TITLE
Include links to the original posts in footnotes/end of chapter

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#60]
Does this provide any value?

**Comment by jared-w** [comment]
I'd say that it could definitely provide value to have a small "related material/discussion" section at the end of the chapter where one could put a link to the original post, any reddit (or other) discussion of the chapter, companion youtube videos by Bart, etc. I'd probably stick to things that are very very closely related (ie by the same author or discussing the author's work explicitly) at the start.

There's a gigantic wealth of information  on the web that's excruciatingly difficult to find because it's hidden inside comment histories, IRC logs, and websites people forget even exist.
