### ISSUE TITLE
Define environment for haskell/C++ highlighting, and one for pseudo-code.

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#71]

**Comment by fosskers** [comment]
I used [these LaTeX settings for Haskell code highlighting](https://github.com/fosskers/crypto-classical/blob/master/crypto-classical.tex#L12) that I found in the depths of the internet a while back. I hope they can help.

**Comment by hmemcpy** [comment]
Awesome! I'll take a look, thank you!

**Comment by jared-w** [comment]
I would suggest looking at the package `minted` for LaTeX for source code highlighting. It handles just about everything for you and is pretty awesome; I use it all the time for programming assignments.

**Comment by hmemcpy** [comment]
Yeah, I'm already using minted in a few places (particularly, because it supports [escaping](https://tex.stackexchange.com/questions/260551/minted-mathescape) nicely). It had some issues with highlighting Haskell-like pseudocode that is prominent throughout the book. In any event, I'll handle it later, after all the typesetting is complete :)

**Comment by jared-w** [comment]
The slightly terrifying method (yet least hackish out there) to do so is this:

1. Write a lexer for pseudo-haskell in a python file (see [this repo](https://github.com/hugomaiavieira/pygments-rspec) for inspiration); name the class something like PseudoHaskell, for example. This should be really easy (in theory) since it should be just copy+paste of the existing Haskell lexer from Pygments itself and then adding a few lines here and there to make it work with the pseudo haskell.
2. Put that pseudo-haskell.py lexer file in the same directory as the main TeX source file
3. Put `\def\phaskell{path/to/pseudo-haskell.py:PseudoHaskell -x}` in your preamble
4. Use `\begin{minted}{\mylexer}` instead of `\begin{minted}{haskell}` and then voila!

(Just writing this for future reference if anyone wants to tackle that).

Related: does anyone happen to know off hand the additional keywords or additions one would make to "normal haskell" highlighting to make it work with the pseudo-haskell examples in the book? It would be great to get that in this issue; that would make this a very easy intro issue.
