### ISSUE TITLE
Acknowledgments page font size changes

### ISSUE THREAD

**Issue by gfixler** [hmemcpy/milewski-ctfp-pdf#83]
In the 3rd paragraph, first sentence, right after the code-formatted word "compose", the rest of the text in the paragraph appears to shrink in size to match the code format size.

The remaining two pages—Colophon and Copyleft notice—also appear to use this reduced-size font in their body text. A quick scan seems to show that the rest of the book uses the larger font as seen in the first two paragraphs of the Acknowledgments.

**Comment by hmemcpy** [comment]
Yep, I see it! Thanks for reporting!
![image](https://user-images.githubusercontent.com/601206/32214459-97698da2-be27-11e7-9e29-80a0dcdcc2b6.png)

**Comment by hmemcpy** [comment]
😱 looking at the bug, this is caused due to the `\code` macro not restoring `\normalsize` font after it's done! (I changed `\code` to `\small`, to match the code snippets)
This caused the rest of the book to change too! This explains the lowered page count and shifted images... I'll have to revert a bunch of things...

**Comment by gfixler** [comment]
Wow! I thought I was seeing it in a few other places. Glad this one got fixed!
